### ISSUE TITLE
Cannot use estimate.hyper() with dplyr/plyr conflict

### ISSUE THREAD

**Issue by CinchBlue** [JohnReid/DeLorean#1]
In `plyr`, `group_by(gene)` fails to give a table with the `gene` column preserved.
In `dplyr`, it does preserve the column.

Other packages that run a process with R and dplyr and plyr both loaded will most likely conflict without the direct namespace reference (e.g. a Shiny app that wants to use both the Monocle and DeLorean package will cause problems).

![delorean_namespace_error](https://cloud.githubusercontent.com/assets/844699/12342444/80006ff4-bace-11e5-8bf8-fb1f20f5140b.png)

**Comment by JohnReid** [comment]
Thanks for pointing this out. I've been trying to eliminate dplyr/plyr conflicts by explicitly referencing the correct namespace. I've obviously yet to catch them all. Please let me know if you find any more issues. John.

**Comment by JohnReid** [comment]
OK I think I have fixed this in this [commit](https://github.com/JohnReid/DeLorean/commit/28fb055c1fdb204d004e81ad417c3cde7fc06251). Please let me know if you have any other similar issues. I'm trying to find them all. For the moment the code is in a bit of a state of flux as I refactor it for submission to CRAN.
