### ISSUE TITLE
Mismatch between arguments in vignette and latest CRAN version

### ISSUE THREAD

**Issue by davismcc** [JohnReid/DeLorean#3]
Hi there

Interesting methods that I'm excited to try on my data. There is a mismatch between the code example for `estimate.hyper` in the vignette:

```
dl <- estimate.hyper(dl, sigma.tau = 0.5, length.scale = 1.5,
+ model.name = 'simple-model')
```

And the actual current version (v1.2.3) downloaded from CRAN today, permits `exact`, `exact-sizes`, `lowrank` and `lowrank-sizes` as valid `model.name` arguments in `estimate.hyper`.

If you're not currently building a live vignette when building the package then I would recommend doing this to avoid this kind of issue.

Best wishes
Davis

**Comment by JohnReid** [comment]
Hi, Thanks for your interest in the method. Where did you get the vignette from? I think I did change this in the [latest version on github](https://github.com/JohnReid/DeLorean/blob/master/vignettes/DeLorean.Rmd).
Kind regards,
John.

**Comment by davismcc** [comment]
This was the vignette that came with the CRAN version of the pkg. 
I initially installed directly from github, but even with "build_vignettes=TRUE" I got an error when trying vignette("DeLorean") and also browseVignettes. That led me to try the CRAN version to get an idea of how to use the pkg. 
BestDavis 

Sent from mobile

On Fri, Jul 1, 2016 at 6:31 PM +0100, "John Reid" notifications@github.com wrote:

Hi, Thanks for your interest in the method. Where did you get the vignette from? I think I did change this in the latest version on github?

Kind regards,

John.

**Comment by JohnReid** [comment]
That's interesting because the PDF on CRAN seems to use the correct arguments. The download archive from CRAN also seems to use the correct arguments so I'm a bit lost as to where this incorrect version comes from. Also I think I am building a live vignette when building the package. I'll close this as it seems to be sorted if unexplained. Let me know if you have any more problems.
